### ISSUE TITLE
Do in-app reviews appear immediately on press?

### ISSUE THREAD

**Issue by ilyakar** [KjellConnelly/react-native-rate#11]
So If I set: `options.preferInApp = true`, does the review prompt appear immediately or does Apple decide the appropriate time to display it?

Sorry, not an issue. I know. But I cannot find a clear answer Googling around.

**Comment by KjellConnelly** [comment]
The review prompt should display immediately (though there is a slightly delay if I remember correctly... similar to when you initialize a view controller from scratch and display it on iOS without caching it). Of course, if the user has already received enough in-app rating prompts, nothing will happen.

**Comment by ilyakar** [comment]
Thank you!
