### ISSUE TITLE
Disabling fallback redirect on iOS

### ISSUE THREAD

**Issue by samdelacruz** [KjellConnelly/react-native-rate#15]
On iOS it would be useful to be able to disable the fallback of opening the App Store if the in-app review process fails.

The reason being - HCI guidelines indicate that the review prompt should not be shown in response to a button press. If a user is performing some positive actions and they are suddenly redirected to the App Store without any prompt, this is hugely irritating.

If redirecting to the app store, we should be displaying some sort of dialog, giving the user the option to rate.

Either this library should implement some sort of customisable dialog, or the redirect after failed in-app rate should be configurable.

Currently because of the redirect, I can't use in-app ratings at all.

Would you be open to some of the changes above?

**Comment by KjellConnelly** [comment]
Yes sir - optional. Will add at some point. Open to pull requests if you’re in a rush :)

**Comment by KjellConnelly** [comment]
Ok I actually just made the changes. Didn't actually test them before deploying... so let me know if there are any problems. There is a not options key in the readme that should do what you're talking about - disabling opening the app store. No new callback though.
