### ISSUE TITLE
Direct users straight to rating section on google play

### ISSUE THREAD

**Issue by mezod** [KjellConnelly/react-native-rate#23]
Hi Kjell,

Got the lib working for Android now :-) but noticed that it redirects to the product page and not the specific rating section of the product page. Is this expected behaviour? Did you try to figure out a way to direct to the rating section? Just making sure if I should invest time into it or not. Thanks again!

Joan

**Comment by KjellConnelly** [comment]
Hi Joan!

I used a url that I used to use for Cordova apps a few years ago. I don’t think there was a way to direct them to the actual review part. Feel free to do some research though. I know Apple has changed their url scheme a few times over the years, so maybe google play has too. I’d love to implement a better url.
