### ISSUE TITLE
How I can check existence review for my app?

### ISSUE THREAD

**Issue by NarekChang** [KjellConnelly/react-native-rate#24]
How I can check existence review for my app? I can use with lib for that? I can't find tutorial's for solution.

**Comment by KjellConnelly** [comment]
Idk what you mean - do you want to know how to check if a user has already reviewed your app before?

**Comment by NarekChang** [comment]
@KjellConnelly yes. Sorry for my english :)

**Comment by KjellConnelly** [comment]
There is no way to reliably check if a user has rated your app. The most you can do is be notified when a user opens the link provided by this module and are taken to the App Store. 

Example:
- User gets a pop up: Please Rate My App. 
- User can tap Yes, or cancel. User taps Yes.
- You save a variable to AsyncStorage that the user tapped yes, but there is no way to know if the user actually went through with rating/reviewing the app. 
- User is taken to your App Review Page. They could leave a rating. They could write a review. They could open up Angry Birds and completely forget about your app. 

So the best you can do is know that a user has opened the link to the App Store. For privacy reasons, there is no way to know if they actually do anything.

Though you can query for app reviews (this module does not do this though), there is no way to reliably compare if the user who wrote a review is the one using your app as there is no identifier that is reliably given within an app review. 

For example, there may be a review given by a user named johndoe365. There also may be a user that you have collected information from before. Maybe you just collected their name, and it is John Doe. So you may assume it’s the same person. But it might not be. Or maybe they signed in with their Google account in your app, and their username is johndoe365. In that case, you could assume it is the same person. But that information would not be 100% the same for every user. So it’s not a reliable way to check if a user has written a review or not.

This also discourages developers from giving rewards for their users rating/reviewing their apps which is actually now allowed. Although, some apps give you freebies for rating their app, you can also bypass this by simply saying you will rate the app, and not doing it.
