### ISSUE TITLE
Android Rate is redirecting to Google Play by default

### ISSUE THREAD

**Issue by RamkumarBPE** [KjellConnelly/react-native-rate#25]
Hi,
 I am implementing react-native-rate, it is working in iOS as a pop-up. In Android it is redirecting to Google Play store(It is not asking pop-up). IS this i the default behaviour? or what might be the issue?

**Comment by RamkumarBPE** [comment]
let options = {
	AppleAppID:"xxx",
	GooglePackageName:"xxx.xxx.xx",
	OtherAndroidURL:"http://goog",
	preferredAndroidMarket: AndroidMarket.Google,
	preferInApp:true,
}

**Comment by KjellConnelly** [comment]
This is the behavior your options call for. The pop up happens due to preferInApp:true on iOS. Android does not have a native way to rate from within the app itself to my knowledge. But if there is a way, this module does not implement that.

This question is already answered in the readme.
