### ISSUE TITLE
Rating an app in Dev

### ISSUE THREAD

**Issue by fhad-getmaple** [KjellConnelly/react-native-rate#3]
The prompt comes up for dev builds, just wondering what happens if I leave a review for a non production build.

Thanks

**Comment by KjellConnelly** [comment]
Which prompt are you referring to?

**Comment by KjellConnelly** [comment]
If you’re referring to SKStoreReviewController, just check out apple’s documentation:

https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview

If you leave a review this way, nothing happens since it’s not production.
