### ISSUE TITLE
Submit Button is Disabled

### ISSUE THREAD

**Issue by prancky** [KjellConnelly/react-native-rate#32]
<img width="301" alt="Screen Shot 2019-04-23 at 7 45 50 PM" src="https://user-images.githubusercontent.com/18732057/56588188-817d0c80-6600-11e9-97b0-9f0a0a23f9dd.png">

**Comment by KjellConnelly** [comment]
Your screenshot is from an app installed via your computer (dev mode), or iOS live App Store (production)? This looks like dev mode to me. If it's not let me know. You can't rate in dev mode, TestFlight, or users who used a promo code to get the app.
