### ISSUE TITLE
[Android] Package name

### ISSUE THREAD

**Issue by batical** [KjellConnelly/react-native-rate#4]
It seems that you are using the default package name 'com.reactlibrary' which created some compilation error on android if another library also use this package

**Comment by KjellConnelly** [comment]
Oh yeah lol. Will fix at some point. I had to fix this in another person’s package While back so I’m familiar with this issue, but it didn’t interfere with the app I’m currently working on. Thanks for the report :)

**Comment by KjellConnelly** [comment]
Hi batical. I think I fixed this, but don't have the time to actually compile at the moment. If you're still using this project and having this issue, give 1.0.7 a whirl and see if it works. I changed the package name to com.RNRate, which hopefully works. Though the android file system is a bit foreign to me, so I may have missed a piece.

**Comment by batical** [comment]
I delay the use of it (have other things to code :D) will give a try today I keep you in touch

**Comment by batical** [comment]
@KjellConnelly project is compiling android/ios . Unfortunately, I don't have the time to implement the usage of your lib today(it is extra work project). i will try it over the week end. Thanks
