### ISSUE TITLE
Pressing Not now wont tell app that user cancels rating.

### ISSUE THREAD

**Issue by pouya92** [KjellConnelly/react-native-rate#40]
Hi, thanks for your great library, I need to know if user close the rating box or actually rate, is there any way to know that?

**Comment by KjellConnelly** [comment]
If you're talking about in in-app rating iOS dialogue, then no, there's no way to find out if the user rated. The best you can do for rating is ask the user to rate something, let them tap something to open up the rating dialogue, and hope they rate/review the app. You can't tell.
