### ISSUE TITLE
Support iOS13 darkmode ?

### ISSUE THREAD

**Issue by t0m0120** [KjellConnelly/react-native-rate#41]
Hi, thanks for your great library

Do you have plans to support dark mode?

**Comment by KjellConnelly** [comment]
Not sure what darkmode has to do with rating. Can you elaborate what ideas you had, or APIs you are referring to?

**Comment by t0m0120** [comment]
@KjellConnelly 
Sorry for poor English

![スクリーンショット 2019-09-02 15 42 11](https://user-images.githubusercontent.com/34805701/64094941-5073cc00-cd98-11e9-9ee4-c1ae752dc2a2.png)

When I try dark mode on iOS 13 of Xcodebeta, the characters
 are white but the background color remains white

**Comment by KjellConnelly** [comment]
I gotcha. That is an iOS issue which I'm sure will be resolved by Apple either before iOS 13 goes live, or soon after. This package uses their native API for that, so it'll be fixed as soon as they fix it. :)

**Comment by t0m0120** [comment]
@KjellConnelly 
I see
Thank you for checking

**Comment by gromdroid** [comment]
Is there any update on this? I'm running the official iOS 13 now and I still get the white dialog while on dark mode

**Comment by KjellConnelly** [comment]
Probably still an issue if you've updated to the latest version of iOS. I suggest submitting a bug report to them. If they get enough, it'll make it more likely they fix it sooner rather than later.

**Comment by samitha9125** [comment]
@KjellConnelly Is this fixed now? Great library btw :)

**Comment by KjellConnelly** [comment]
Thanks! Though I haven't verified it myself, I did read a SO post from 2019 that says that it was fixed. So I assume it is.
