### ISSUE TITLE
Cannot install on RN 0.60+

### ISSUE THREAD

**Issue by felixchan** [KjellConnelly/react-native-rate#43]
After yarn install and `react-native link`, I see a line added to Podfile.

I run `pod install` and receive:

[!] No podspec found for `RNRate` in `../node_modules/react-native-rate`

When I build (without running pod install), I receive Folly error.

`/project/Pods/Folly/folly/detail/RangeCommon.h:22:10: 'glog/logging.h' file not found` (But fixed this after removing Podfile.lock , unlinking, removing package, and running pod install again)

**Comment by jayli3n** [comment]
in your podfile, change the line to: `pod 'RNRate', :path => '../node_modules/react-native-rate/ios'`
it's good until they file the file structure.

**Comment by DevArenaCN** [comment]
@felixchan @jayli3n I changed the podfile to 
```
pod 'RNRate', :path => '../node_modules/react-native-rate'
```
and it builds fine.

**Comment by KjellConnelly** [comment]
Moved the podspec file to `../node_modules/react-native-rate` instead of inside the ios folder. If you update, you will probably need to change your project's podspec file.
