### ISSUE TITLE
Open Google Play Store app instead of a chooser

### ISSUE THREAD

**Issue by xwartz** [KjellConnelly/react-native-rate#44]
Hey,

Due to url `http://play.google.com/store/apps/details?id=`, the action to be performed could be handled by multiple apps and the user might prefer a different app each time. So it will show a chooser dialog as shown:

https://developer.android.com/training/basics/intents/sending#AppChooser

![image](https://user-images.githubusercontent.com/4149827/65008819-2c3df080-d93d-11e9-8d40-74aa5ed742e8.png)

The chooser dialog forces the user to select which app to use for the action every time (the user cannot select a default app for the action).

I think we can use [Linking from an Android App](https://developer.android.com/distribute/marketing-tools/linking-to-google-play#android-app), so that users can see app's details in the Google Play Store app instead of a chooser.

**Comment by KjellConnelly** [comment]
That's a great idea :) I'm pretty busy with other things and still stuck with RN 0.40 at the moment, and would like to upgrade to the latest before I work on this intent. But if you or someone else wants to work on it and make a PR I would be fine with that :)
