### ISSUE TITLE
Is autolink support planned?

### ISSUE THREAD

**Issue by mi5ha** [KjellConnelly/react-native-rate#46]
Hi there, very useful plugin, but it needs to be updated to support autolinking. Is that planned?

**Comment by KjellConnelly** [comment]
I'm not on RN0.60+ yet, so adding it anytime soon is not a priority. Pull requests are welcome, though I've never used auto linking, so can't verify personally if the request is valid.

**Comment by mi5ha** [comment]
Current installation method reports error on RN0.60+ so it have to be solved at some point.

**Comment by aitorct** [comment]
https://github.com/KjellConnelly/react-native-rate/pull/47 solves this
