### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by nswekosk** [KjellConnelly/react-native-rate#50]
I've completed the installation process using iOS and CocoaPods and am now testing on the iOS Simulator. My callback is returning success but nothing happens.

~Is this supposed to redirect the user to the App Store app and to my app's App Store record to provide a review? Or is this supposed to open a WebView to enable a user to submit a rating over http?~

~I'm using the example found here:~
~- https://github.com/KjellConnelly/react-native-rate~

~React-Native: 0.59.3~
Edit: October 31st, 2019; 11:52AM
Resolved by viewing the following:
- https://github.com/KjellConnelly/react-native-rate#what-this-module-does-when-you-call-rate

New Question: Is it supposed to work on the iOS simulator?

**Comment by KjellConnelly** [comment]
I don't remember if it works on the simulator or not. I think that if you use the iOS in app review, it should display some of the UI (up to 3x). Other ways should open up the App Store. If your app isn't live yet, it'll probably goto a page saying that the app doesn't exist.

**Comment by nswekosk** [comment]
Thanks @KjellConnelly. Out of curiosity, did you implement this to only display 3 times or is that due to a limit from a third-party source? If you implemented it to display 3 times at most, how come?

**Comment by KjellConnelly** [comment]
It uses the native SKStoreReviewController. Apple limits developers to ask the user a max of 3x per year, without any feedback to the developer if it worked or not. So you have to track it yourself if you want to make sure you don't exceed that number of calls. You can google that controller to get all the details on it.

**Comment by nswekosk** [comment]
Thank you for the context

**Comment by nihp** [comment]
@nswekosk I am trying to implement this in the simulator. Does it work in the simulator?

If not how can I check this?

**Comment by KjellConnelly** [comment]
Not 100% sure but when I wrote this a couple years ago, I think it would open the SKStoreReviewController pop up on iOS in simulator up to 3x. You can google if there is different behavior now. 

As far as opening the iOs App Store on simulator, I think it doesn't work. And I completely forget for Google Play.

**Comment by nihp** [comment]
@KjellConnelly I have opened the popup in my simulator too after successfully rated does I need to add navigation to the App store?

Or what will be done here to enable the Submit button in the popup screen?

Note: I have used your example code snippet in this package
![Screenshot 2020-01-24 at 5 36 44 PM](https://user-images.githubusercontent.com/36992338/73067991-1bdfe880-3ed0-11ea-8cfb-ea556ee1b0ff.png)

**Comment by KjellConnelly** [comment]
That's all you need to do. Once the user taps Submit, they will be asked if they want to write a review as well.
