### ISSUE TITLE
Can we get this working for react-native 0.60+?

### ISSUE THREAD

**Issue by jacquesdev** [KjellConnelly/react-native-rate#55]
Could we please get this updated so that for example, we no longer need to link packages?

I'm assuming we'd get warnings in its current form, and it does seem to have existing issues https://github.com/KjellConnelly/react-native-rate/issues/43

**Comment by KjellConnelly** [comment]
I can update it for iOS today (I'm currently working on updating one of my own apps, iOS first, but haven't even installed android on my new computer so it'll be awhile before I get around to testing any problems on Android

**Comment by KjellConnelly** [comment]
Ok, I think the problem was that I didn't update the npm package, but the github repo had autolinking setup. Just installed this package into my new `react-native` v0.62 project and it worked great for iOS.

**Comment by jacquesdev** [comment]
Thank you!
