### ISSUE TITLE
In-app review for Android with PlayCore

### ISSUE THREAD

**Issue by sregg** [KjellConnelly/react-native-rate#62]
See the news: https://android-developers.googleblog.com/2020/08/in-app-review-api.html
See the API: https://developer.android.com/guide/playcore/in-app-review

I'd be happy to start working on a PR if the maintainers are interested in that.

**Comment by KjellConnelly** [comment]
That'd be really cool if you added this feature :) I don't spend much time coding lately, and I've always been much more proficient in Obj-C/Swift and JavaScript than Java, so hopefully you can do thorough testing since I probably won't do much until I get back into updating my current RN app.

**Comment by sregg** [comment]
I already have something working
![Screenshot_20200805-180241.png](https://user-images.githubusercontent.com/1479283/89468766-25cb8980-d746-11ea-9dda-319a64094ea4.png)
![Screenshot_20200805-180343.png](https://user-images.githubusercontent.com/1479283/89468772-282de380-d746-11ea-9e6c-097d1dd841b1.png)
I just need to follow the same logic as iOS with the options (e.g. preferInApp, openAppStoreIfInAppFails, etc...).
And update the README

**Comment by TayyabaAslam3317** [comment]
Please update when it is merged.

**Comment by KjellConnelly** [comment]
Alright - just merged the github version, made a few changes to README.md, and pushed to npm. Should be ready to use. Let me and @sregg if there are any issues. And thank you @sregg 👍
