### ISSUE TITLE
import androidx.annotation.NonNull

### ISSUE THREAD

**Issue by jigartankhupp** [KjellConnelly/react-native-rate#68]
**Additional Information**
"react-native-rate": "^1.2.4",
"react": "16.8.3",
"react-native": "0.59.9",
Platform(s) (iOS, Android, or both?): Android
Operating System : macOS

**Error**
/node_modules/react-native-rate/android/src/main/java/com/reactnativerate/RNRateModule.java:4: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation

public void onComplete(@NonNull final Task<ReviewInfo> requestTask) {
                                    ^
  symbol: class NonNull

**Comment by rafauke** [comment]
Have you jetified your modules?

```
npx jetify
```
