### ISSUE TITLE
TypeError: null is not an object (evaluating 'RNRate.rate') [ANDROID]

### ISSUE THREAD

**Issue by AdamGerthel** [KjellConnelly/react-native-rate#69]
I've just upgraded from 1.2.1 to 1.2.4 and I'm getting this error on Android (not iOS!)

## Error description

> TypeError: null is not an object (evaluating 'RNRate.rate')

See screenshot below:

![Screenshot 2020-09-01 at 10 38 32](https://user-images.githubusercontent.com/1490370/91827578-4d2b4e80-ec3f-11ea-8c2e-1b112ab00166.png)

## Code sample

```
import Rate from 'react-native-rate'

// ...

    Rate.rate({
      AppleAppID: config.appStoreId,
      GooglePackageName: config.androidPackageName,
      preferInApp: true
    }, success => {
        // Removed my code here since it's not relevant to the error
    })
```

## Misc info

React Native: 0.63.2
React Native Rate: 1.2.4

Tested on real device

**Comment by AdamGerthel** [comment]
Also, the readme states:

> Android, Windows, etc don't use any native code. So don't worry! (There still is linking to Android if you do react-native link. We only left this here so that we can call native code if there is native code to call someday.)

But that doesn't seem to be the case any longer, no?

**Comment by AdamGerthel** [comment]
Ended up being an issue with linking

**Comment by dilipsuthar97** [comment]
Anyone solved the above issue, I'm facing the same issue right now.
