### ISSUE TITLE
Is it possible to change default text and language that is shown on popup?

### ISSUE THREAD

**Issue by annaostapenko22** [KjellConnelly/react-native-rate#76]
Hi! How can I change the text "Enjoying <App Name>? Tap a star to rate..."
And also, is it possible to change the text or language on buttons "not now", "cancel", "submit"?

**Comment by KjellConnelly** [comment]
Not to my knowledge. It uses the standard API, which back when I wrote this didn't have such an option. You can check though. Maybe they updated something.
