### ISSUE TITLE
[iOS] In App Rating is below the rest of the app

### ISSUE THREAD

**Issue by Michaellumibao** [KjellConnelly/react-native-rate#78]
It could have something to do with z-index? However, the view is created using the `Rate.rate` function so I'm not entirely sure how to change the z-index or if it even fixes the issue.

![Image from iOS (15)](https://user-images.githubusercontent.com/31720028/105101047-467d6680-5a7c-11eb-98b0-ed1ae53fd647.gif)

**Comment by KjellConnelly** [comment]
I'm guessing it has something to do with react native modals. Try to install the new version of this plugin. It added some new code which hopefully will add it to the active scene. I'm not sure if this will fix the issue, but it potentially will. Let me know if you're still having this problem or if the fix does anything. Closing for now.
