### ISSUE TITLE
Neither rating dilog opens nor it redirect me to the store.

### ISSUE THREAD

**Issue by khushbooOpenxcell** [KjellConnelly/react-native-rate#80]
Hello,
I am working on an android application which was already built and published on play store and now i'm translating the whole code to react native.

I have used this library which works well on iOS but not on android. 
I have not rated the application before and also i'm new to android platform. What would have been missed by me?

**Comment by B4ckes** [comment]
I'm having the same problem on the app that i work in, for me, in the android emulator i have no rating pop up, but i'm redirected to play store web page on chrome, but, in the physical device nothing happens.

OBS.: I'm receiving a true boolean flag on success callback.

**Comment by Pyroboomka** [comment]
Same issue as @B4ckes, store link on emulator, success callback and nothing happening on physical device.

**Comment by odedmagger** [comment]
Same issue (physical device, Samsung Galaxy S9 with Android 10, app not published to the store yet but in closed testing track).

If only the result was `success === false`, at least I could've implemented a workaround.

**Comment by sriksm19** [comment]
hi. i just tested the app. It doesnt work directly (running on dev or even through installing a release apk). spent a couple of hours on this, and on another lib called **https://github.com/MinaSamir11/react-native-in-app-review**. neither worked. Then I headed over to the docs to read again for the aha moment:
![image](https://user-images.githubusercontent.com/1223117/121171945-c9109200-c874-11eb-927a-e545f6241484.png)
so i headed to my play console, created an internal testing release, downloaded and tested the app via that and it worked well.

I would like to suggest you to create an internal testing release n try out. :D

**Comment by odedmagger** [comment]
Thanks. I did test this on the Internal Testing release, to no avail.

**Comment by apfritts** [comment]
I just updated to 1.2.6 and it seems to work now 🤷🏻‍♂️
