### ISSUE TITLE
[iOS] App Rating in App not showing in Testflight

### ISSUE THREAD

**Issue by PaperbagWriter** [KjellConnelly/react-native-rate#82]
This is maybe more of a question or something to add to the documentation.
While developing the feature/adding in-app rating I was able to see it but on Testflight it never prompts me.

Is this known / normal?

**Comment by PaperbagWriter** [comment]
Just found the answer here :
https://stackoverflow.com/a/47048474

maybe it could be added to the documentation?

**Comment by KjellConnelly** [comment]
Hey @PaperbagWriter, thanks for the Q and A. Just added this tidbit to the README :)
