### ISSUE TITLE
Unused `options` parameter in Android implementation

### ISSUE THREAD

**Issue by kennyx46** [KjellConnelly/react-native-rate#93]
Just out of curiosity, why do we have some `android` specific fields in the `options` object considering the whole `options` parameter is completely ignored in android implementation? This seems a bit strange and wrong.

![image](https://user-images.githubusercontent.com/3941650/139252404-72d39d68-6874-404f-bc69-4820537bbf33.png)

**Comment by KjellConnelly** [comment]
I just left them there to keep the functions as close to the same for js, objc, and java. Keeping those there allows the options to be used should they need to be in the future.
