### ISSUE TITLE
Declaration of 'RCTConvert' must be imported from module 'React.RCTConvert' before it is required

### ISSUE THREAD

**Issue by MrXyfir** [KjellConnelly/react-native-rate#95]
Attempting to build causes this error:

![image](https://user-images.githubusercontent.com/12347375/148596933-1d60bd4d-a85f-4052-b276-ea79d6f1d8f7.png)

RN 0.64.3
Expo 44
xcode 13.1

This started happening after upgrading Expo from v43 to v44. If I uninstall `react-native-rate`, the app builds.

**Comment by MrXyfir** [comment]
Solution: #96

**Comment by ConorCorp** [comment]
Seeing this issue as well
